global:
  scrape_interval: 1s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["localhost:9100"]

  - job_name: "turbostat_exporter"
    static_configs:
      - targets: ["localhost:9101"]

# Uncomment this for msu-manager metrics
  # - job_name: "msu_manager"
  #   metrics_path: "/api/metrics/"
  #   static_configs:
  #     - targets: ["localhost:8000"]
